### ISSUE TITLE
tags missing for v2.3.2, v2.3.3, and v2.3.4

### ISSUE THREAD

**Issue by eighthave** [WithSecureLabs/drozer-agent#5]
Thanks for drozer!  We're working now to integrating it into the whole f-droid stack, and running it on all apps built for f-droid.org.  In the process, we found that in git, drozer-agent is marked as 2.3.3, and there are no tags for v2.3.2, v2.3.3, and v2.3.4.

Also, the APK for v2.3.4 recently vanished from the site, perhaps due to a site reorg:
https://labs.mwrinfosecurity.com/tools/drozer/
https://labs.mwrinfosecurity.com/system/assets/934/original/drozer-agent-2.3.4.apk

**Comment by HenryHoggard** [comment]
Hi @eighthave, I'm aware of the missing links on the website, I've made a request to have them fixed. For now I have uploaded them https://github.com/mwrlabs/drozer/releases

**Comment by HenryHoggard** [comment]
I'll look into the tags now for you.

**Comment by eighthave** [comment]
Thanks, that was fast.  Also, it seems that there has been work done on drozer-agent since 2014, but the latest commit in this git is 2014-01-18 05bb788dc39d8def9119f626fb03fb76b30a1d00.  Can you push the latest commits too?

@darknetj there is the missing APK you need

**Comment by HenryHoggard** [comment]
I don't believe there has been any work done to the agent since that commit. However I will get a confirmation of that for you.

**Comment by eighthave** [comment]
ah, I see, the whole drozer suite has the same version numbers.  I was
assuming that version number was just for drozer-agent
